
sequenceDiagram

participant Alice

participant Box

participant Bob

Note left of Alice: - Create DID <br/> 
Note left of Alice: - AsymEncryption(init) <br/> - Import PivateKey <br/> - Get PublicKey <br/>

Note right of Bob: - Create DID <br/>
Note right of Bob: - AsymEncryption(init) <br/> - Import PivateKey <br/> - Get PublicKey <br/>

Alice->>Box: Chunked stream Cip = Encryption(m,sK1)

Note right of Box: Save Encrypted Content into IPFS

Box->>Alice: return CID

Bob->>Alice: Send Public Addresses (B^PubKey)

Alice->>Bob: JWE = AsymEncrypt(PubKey, Doc={CID,sK1}

Note right of Bob: - Save JWE <br/>

Bob->>Bob: Doc={CID,sK1} = AsymDecrypt(JWE)

Bob->>Box: Send CID

Box->>Bob: Encrypted stream -> Decryption(Cip,sK1)
